language: ruby
rvm:
 - 2.0
 - 2.1
 - 2.2
 - jruby
 - jruby-1.7
 - jruby-head
 - rbx-2
services:
 - rabbitmq
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
